# Generated by Django 4.2.3 on 2023-08-11 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                error_messages={
                    "unique": "A user is already registered with this e-mail address"
                },
                max_length=254,
                unique=True,
            ),
        ),
    ]
